#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="${TEST_PROJECT_ROOT:-$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../.. && pwd )}"
LOG_DIR="$BASE_DIR/logs"
mkdir -p "$LOG_DIR"

echo "composer $*" >>"$LOG_DIR/composer.log"
